#if !canImport(ObjectiveC)
import XCTest

extension QueryParameterRouteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueryParameterRouteTests = [
        ("testCustomType", testCustomType),
        ("testCustomTypeFails", testCustomTypeFails),
        ("testInt", testInt),
        ("testIntFailing", testIntFailing),
        ("testNotMatching", testNotMatching),
        ("testString", testString),
    ]
}

extension RoutingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RoutingTests = [
        ("testAny", testAny),
        ("testBasic", testBasic),
        ("testMultipleMatchers", testMultipleMatchers),
        ("testSpecificMatcher", testSpecificMatcher),
        ("testStringLiterals", testStringLiterals),
        ("testTwoURLParameters", testTwoURLParameters),
        ("testURLParameters", testURLParameters),
    ]
}

extension URLParameterRouteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLParameterRouteTests = [
        ("testCustomType", testCustomType),
        ("testCustomTypeFails", testCustomTypeFails),
        ("testInt", testInt),
        ("testIntFailing", testIntFailing),
        ("testNotMatching", testNotMatching),
        ("testString", testString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(QueryParameterRouteTests.__allTests__QueryParameterRouteTests),
        testCase(RoutingTests.__allTests__RoutingTests),
        testCase(URLParameterRouteTests.__allTests__URLParameterRouteTests),
    ]
}
#endif
